package info.javaknowledge.projectstarter.domain;
// Generated Jan 25, 2018 6:45:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BatchInfo generated by hbm2java
 */
@Entity
@Table(name="batch_info"
    ,catalog="tsp"
)
public class BatchInfo  implements java.io.Serializable {


     private Integer batchId;
     private TspInfo tspInfo;
     private String batchName;
     private Date startDate;
     private Date endDate;
     private int batchRound;
     private Set<StudentInfo> studentInfos = new HashSet<StudentInfo>(0);
     private Set<ExamSchedule> examSchedules = new HashSet<ExamSchedule>(0);

    public BatchInfo() {
    }

	
    public BatchInfo(TspInfo tspInfo, String batchName, Date startDate, Date endDate, int batchRound) {
        this.tspInfo = tspInfo;
        this.batchName = batchName;
        this.startDate = startDate;
        this.endDate = endDate;
        this.batchRound = batchRound;
    }
    public BatchInfo(TspInfo tspInfo, String batchName, Date startDate, Date endDate, int batchRound, Set<StudentInfo> studentInfos, Set<ExamSchedule> examSchedules) {
       this.tspInfo = tspInfo;
       this.batchName = batchName;
       this.startDate = startDate;
       this.endDate = endDate;
       this.batchRound = batchRound;
       this.studentInfos = studentInfos;
       this.examSchedules = examSchedules;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="batch_id", unique=true, nullable=false)
    public Integer getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tsp_id", nullable=false)
    public TspInfo getTspInfo() {
        return this.tspInfo;
    }
    
    public void setTspInfo(TspInfo tspInfo) {
        this.tspInfo = tspInfo;
    }

    
    @Column(name="batch_name", nullable=false, length=30)
    public String getBatchName() {
        return this.batchName;
    }
    
    public void setBatchName(String batchName) {
        this.batchName = batchName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date", nullable=false, length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_date", nullable=false, length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="batch_round", nullable=false)
    public int getBatchRound() {
        return this.batchRound;
    }
    
    public void setBatchRound(int batchRound) {
        this.batchRound = batchRound;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="batchInfo")
    public Set<StudentInfo> getStudentInfos() {
        return this.studentInfos;
    }
    
    public void setStudentInfos(Set<StudentInfo> studentInfos) {
        this.studentInfos = studentInfos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="batchInfo")
    public Set<ExamSchedule> getExamSchedules() {
        return this.examSchedules;
    }
    
    public void setExamSchedules(Set<ExamSchedule> examSchedules) {
        this.examSchedules = examSchedules;
    }




}


