package info.javaknowledge.projectstarter.domain;
// Generated Jan 25, 2018 6:45:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExamSchedule generated by hbm2java
 */
@Entity
@Table(name="exam_schedule"
    ,catalog="tsp"
)
public class ExamSchedule  implements java.io.Serializable {


     private Integer examId;
     private BatchInfo batchInfo;
     private TspFaculty tspFaculty;
     private TspInfo tspInfo;
     private String examName;
     private Date examDate;
     private double totalMarks;
     private Set<ExamMarks> examMarkses = new HashSet<ExamMarks>(0);

    public ExamSchedule() {
    }

	
    public ExamSchedule(BatchInfo batchInfo, TspFaculty tspFaculty, TspInfo tspInfo, String examName, Date examDate, double totalMarks) {
        this.batchInfo = batchInfo;
        this.tspFaculty = tspFaculty;
        this.tspInfo = tspInfo;
        this.examName = examName;
        this.examDate = examDate;
        this.totalMarks = totalMarks;
    }
    public ExamSchedule(BatchInfo batchInfo, TspFaculty tspFaculty, TspInfo tspInfo, String examName, Date examDate, double totalMarks, Set<ExamMarks> examMarkses) {
       this.batchInfo = batchInfo;
       this.tspFaculty = tspFaculty;
       this.tspInfo = tspInfo;
       this.examName = examName;
       this.examDate = examDate;
       this.totalMarks = totalMarks;
       this.examMarkses = examMarkses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="exam_id", unique=true, nullable=false)
    public Integer getExamId() {
        return this.examId;
    }
    
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="batch_id", nullable=false)
    public BatchInfo getBatchInfo() {
        return this.batchInfo;
    }
    
    public void setBatchInfo(BatchInfo batchInfo) {
        this.batchInfo = batchInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="faculty_id", nullable=false)
    public TspFaculty getTspFaculty() {
        return this.tspFaculty;
    }
    
    public void setTspFaculty(TspFaculty tspFaculty) {
        this.tspFaculty = tspFaculty;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tsp_id", nullable=false)
    public TspInfo getTspInfo() {
        return this.tspInfo;
    }
    
    public void setTspInfo(TspInfo tspInfo) {
        this.tspInfo = tspInfo;
    }

    
    @Column(name="exam_name", nullable=false, length=30)
    public String getExamName() {
        return this.examName;
    }
    
    public void setExamName(String examName) {
        this.examName = examName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="exam_date", nullable=false, length=19)
    public Date getExamDate() {
        return this.examDate;
    }
    
    public void setExamDate(Date examDate) {
        this.examDate = examDate;
    }

    
    @Column(name="total_marks", nullable=false, precision=22, scale=0)
    public double getTotalMarks() {
        return this.totalMarks;
    }
    
    public void setTotalMarks(double totalMarks) {
        this.totalMarks = totalMarks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="examSchedule")
    public Set<ExamMarks> getExamMarkses() {
        return this.examMarkses;
    }
    
    public void setExamMarkses(Set<ExamMarks> examMarkses) {
        this.examMarkses = examMarkses;
    }




}


