package info.javaknowledge.projectstarter.domain;
// Generated Feb 5, 2018 12:52:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExamMarks generated by hbm2java
 */
@Entity
@Table(name="exam_marks"
    ,catalog="tsp"
)
public class ExamMarks  implements java.io.Serializable {


     private Integer marksId;
     private ExamSchedule examSchedule;
     private StudentInfo studentInfo;
     private double marksObtained;

    public ExamMarks() {
    }

    public ExamMarks(ExamSchedule examSchedule, StudentInfo studentInfo, double marksObtained) {
       this.examSchedule = examSchedule;
       this.studentInfo = studentInfo;
       this.marksObtained = marksObtained;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="marks_id", unique=true, nullable=false)
    public Integer getMarksId() {
        return this.marksId;
    }
    
    public void setMarksId(Integer marksId) {
        this.marksId = marksId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="exam_id", nullable=false)
    public ExamSchedule getExamSchedule() {
        return this.examSchedule;
    }
    
    public void setExamSchedule(ExamSchedule examSchedule) {
        this.examSchedule = examSchedule;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false)
    public StudentInfo getStudentInfo() {
        return this.studentInfo;
    }
    
    public void setStudentInfo(StudentInfo studentInfo) {
        this.studentInfo = studentInfo;
    }

    
    @Column(name="marks_obtained", nullable=false, precision=22, scale=0)
    public double getMarksObtained() {
        return this.marksObtained;
    }
    
    public void setMarksObtained(double marksObtained) {
        this.marksObtained = marksObtained;
    }




}


