package info.javaknowledge.projectstarter.domain;
// Generated Jan 25, 2018 6:45:30 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * LoginInfo generated by hbm2java
 */
@Entity
@Table(name = "login_info",
         catalog = "tsp",
         uniqueConstraints = @UniqueConstraint(columnNames = "user_name")
)
public class LoginInfo implements java.io.Serializable {

    private Integer loginId;
    private TspInfo tspInfo;
    private UserRole userRole;

    private String userName;
    private String userPassword;
    private int status;

    public LoginInfo() {
    }

    public LoginInfo(TspInfo tspInfo, UserRole userRole, int userId, String userPassword, int status) {
        this.tspInfo = tspInfo;
        this.userRole = userRole;

        this.userPassword = userPassword;
        this.status = status;
    }

    public LoginInfo(TspInfo tspInfo, UserRole userRole, String userName, String userPassword, int status) {
        this.tspInfo = tspInfo;
        this.userRole = userRole;

        this.userName = userName;
        this.userPassword = userPassword;
        this.status = status;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "login_id", unique = true, nullable = false)
    public Integer getLoginId() {
        return this.loginId;
    }

    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tsp_id", nullable = false)
    public TspInfo getTspInfo() {
        return this.tspInfo;
    }

    public void setTspInfo(TspInfo tspInfo) {
        this.tspInfo = tspInfo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "role_id", nullable = false)
    public UserRole getUserRole() {
        return this.userRole;
    }

    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }

    @Column(name = "user_name", unique = true, length = 30)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "user_password", nullable = false, length = 20)
    public String getUserPassword() {
        return this.userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    @Column(name = "status", nullable = false)
    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

}
