package info.javaknowledge.projectstarter.domain;
// Generated Jan 25, 2018 6:45:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentJobStatus generated by hbm2java
 */
@Entity
@Table(name="student_job_status"
    ,catalog="tsp"
)
public class StudentJobStatus  implements java.io.Serializable {


     private Integer jobId;
     private StudentInfo studentInfo;
     private String companyName;
     private Date joiningDate;
     private double startingSalary;
     private String jobPosition;
     private String companyLocation;
     private Date resignDate;
     private int status;

    public StudentJobStatus() {
    }

    public StudentJobStatus(StudentInfo studentInfo, String companyName, Date joiningDate, double startingSalary, String jobPosition, String companyLocation, Date resignDate, int status) {
       this.studentInfo = studentInfo;
       this.companyName = companyName;
       this.joiningDate = joiningDate;
       this.startingSalary = startingSalary;
       this.jobPosition = jobPosition;
       this.companyLocation = companyLocation;
       this.resignDate = resignDate;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="job_id", unique=true, nullable=false)
    public Integer getJobId() {
        return this.jobId;
    }
    
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false)
    public StudentInfo getStudentInfo() {
        return this.studentInfo;
    }
    
    public void setStudentInfo(StudentInfo studentInfo) {
        this.studentInfo = studentInfo;
    }

    
    @Column(name="company_name", nullable=false, length=30)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="joining_date", nullable=false, length=19)
    public Date getJoiningDate() {
        return this.joiningDate;
    }
    
    public void setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }

    
    @Column(name="starting_salary", nullable=false, precision=22, scale=0)
    public double getStartingSalary() {
        return this.startingSalary;
    }
    
    public void setStartingSalary(double startingSalary) {
        this.startingSalary = startingSalary;
    }

    
    @Column(name="job_position", nullable=false, length=30)
    public String getJobPosition() {
        return this.jobPosition;
    }
    
    public void setJobPosition(String jobPosition) {
        this.jobPosition = jobPosition;
    }

    
    @Column(name="company_location", nullable=false, length=45)
    public String getCompanyLocation() {
        return this.companyLocation;
    }
    
    public void setCompanyLocation(String companyLocation) {
        this.companyLocation = companyLocation;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="resign_date", nullable=false, length=19)
    public Date getResignDate() {
        return this.resignDate;
    }
    
    public void setResignDate(Date resignDate) {
        this.resignDate = resignDate;
    }

    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


