package info.javaknowledge.projectstarter.domain;
// Generated Jan 25, 2018 6:45:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentInfo generated by hbm2java
 */
@Entity
@Table(name="student_info"
    ,catalog="tsp"
)
public class StudentInfo  implements java.io.Serializable {


     private Integer studentId;
     private BatchInfo batchInfo;
     private TspInfo tspInfo;
     private String studentName;
     private String studentAddress;
     private String studentEmail;
     private String studentPhone;
     private String studentFatherName;
     private String studentMotherName;
     private Date studentDateOfBirth;
     private String studentNid;
     private String studentPhoneLink;
     private Set<StudentJobStatus> studentJobStatuses = new HashSet<StudentJobStatus>(0);

    public StudentInfo() {
    }

	
    public StudentInfo(BatchInfo batchInfo, TspInfo tspInfo, String studentName, String studentAddress, String studentEmail, String studentPhone, String studentFatherName, String studentMotherName, Date studentDateOfBirth, String studentNid, String studentPhoneLink) {
        this.batchInfo = batchInfo;
        this.tspInfo = tspInfo;
        this.studentName = studentName;
        this.studentAddress = studentAddress;
        this.studentEmail = studentEmail;
        this.studentPhone = studentPhone;
        this.studentFatherName = studentFatherName;
        this.studentMotherName = studentMotherName;
        this.studentDateOfBirth = studentDateOfBirth;
        this.studentNid = studentNid;
        this.studentPhoneLink = studentPhoneLink;
    }
    public StudentInfo(BatchInfo batchInfo, TspInfo tspInfo, String studentName, String studentAddress, String studentEmail, String studentPhone, String studentFatherName, String studentMotherName, Date studentDateOfBirth, String studentNid, String studentPhoneLink, Set<StudentJobStatus> studentJobStatuses) {
       this.batchInfo = batchInfo;
       this.tspInfo = tspInfo;
       this.studentName = studentName;
       this.studentAddress = studentAddress;
       this.studentEmail = studentEmail;
       this.studentPhone = studentPhone;
       this.studentFatherName = studentFatherName;
       this.studentMotherName = studentMotherName;
       this.studentDateOfBirth = studentDateOfBirth;
       this.studentNid = studentNid;
       this.studentPhoneLink = studentPhoneLink;
       this.studentJobStatuses = studentJobStatuses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="student_id", unique=true, nullable=false)
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="batch_id", nullable=false)
    public BatchInfo getBatchInfo() {
        return this.batchInfo;
    }
    
    public void setBatchInfo(BatchInfo batchInfo) {
        this.batchInfo = batchInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tsp_id", nullable=false)
    public TspInfo getTspInfo() {
        return this.tspInfo;
    }
    
    public void setTspInfo(TspInfo tspInfo) {
        this.tspInfo = tspInfo;
    }

    
    @Column(name="student_name", nullable=false, length=30)
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    
    @Column(name="student_address", nullable=false, length=50)
    public String getStudentAddress() {
        return this.studentAddress;
    }
    
    public void setStudentAddress(String studentAddress) {
        this.studentAddress = studentAddress;
    }

    
    @Column(name="student_email", nullable=false, length=30)
    public String getStudentEmail() {
        return this.studentEmail;
    }
    
    public void setStudentEmail(String studentEmail) {
        this.studentEmail = studentEmail;
    }

    
    @Column(name="student_phone", nullable=false, length=11)
    public String getStudentPhone() {
        return this.studentPhone;
    }
    
    public void setStudentPhone(String studentPhone) {
        this.studentPhone = studentPhone;
    }

    
    @Column(name="student_father_name", nullable=false, length=30)
    public String getStudentFatherName() {
        return this.studentFatherName;
    }
    
    public void setStudentFatherName(String studentFatherName) {
        this.studentFatherName = studentFatherName;
    }

    
    @Column(name="student_mother_name", nullable=false, length=30)
    public String getStudentMotherName() {
        return this.studentMotherName;
    }
    
    public void setStudentMotherName(String studentMotherName) {
        this.studentMotherName = studentMotherName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="student_date_of_birth", nullable=false, length=19)
    public Date getStudentDateOfBirth() {
        return this.studentDateOfBirth;
    }
    
    public void setStudentDateOfBirth(Date studentDateOfBirth) {
        this.studentDateOfBirth = studentDateOfBirth;
    }

    
    @Column(name="student_nid", nullable=false, length=30)
    public String getStudentNid() {
        return this.studentNid;
    }
    
    public void setStudentNid(String studentNid) {
        this.studentNid = studentNid;
    }

    
    @Column(name="student_phone_link", nullable=false, length=11)
    public String getStudentPhoneLink() {
        return this.studentPhoneLink;
    }
    
    public void setStudentPhoneLink(String studentPhoneLink) {
        this.studentPhoneLink = studentPhoneLink;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentInfo")
    public Set<StudentJobStatus> getStudentJobStatuses() {
        return this.studentJobStatuses;
    }
    
    public void setStudentJobStatuses(Set<StudentJobStatus> studentJobStatuses) {
        this.studentJobStatuses = studentJobStatuses;
    }




}


