package info.javaknowledge.projectstarter.domain;
// Generated Jan 25, 2018 6:45:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TspFaculty generated by hbm2java
 */
@Entity
@Table(name="tsp_faculty"
    ,catalog="tsp"
)
public class TspFaculty  implements java.io.Serializable {


     private Integer facultyId;
     private TspInfo tspInfo;
     private int facultyCode;
     private String facultyName;
     private String facultyEmail;
     private String facultyPhone;
     private Set<ExamSchedule> examSchedules = new HashSet<ExamSchedule>(0);

    public TspFaculty() {
    }

	
    public TspFaculty(TspInfo tspInfo, int facultyCode, String facultyName, String facultyEmail, String facultyPhone) {
        this.tspInfo = tspInfo;
        this.facultyCode = facultyCode;
        this.facultyName = facultyName;
        this.facultyEmail = facultyEmail;
        this.facultyPhone = facultyPhone;
    }
    public TspFaculty(TspInfo tspInfo, int facultyCode, String facultyName, String facultyEmail, String facultyPhone, Set<ExamSchedule> examSchedules) {
       this.tspInfo = tspInfo;
       this.facultyCode = facultyCode;
       this.facultyName = facultyName;
       this.facultyEmail = facultyEmail;
       this.facultyPhone = facultyPhone;
       this.examSchedules = examSchedules;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="faculty_id", unique=true, nullable=false)
    public Integer getFacultyId() {
        return this.facultyId;
    }
    
    public void setFacultyId(Integer facultyId) {
        this.facultyId = facultyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tsp_id", nullable=false)
    public TspInfo getTspInfo() {
        return this.tspInfo;
    }
    
    public void setTspInfo(TspInfo tspInfo) {
        this.tspInfo = tspInfo;
    }

    
    @Column(name="faculty_code", nullable=false)
    public int getFacultyCode() {
        return this.facultyCode;
    }
    
    public void setFacultyCode(int facultyCode) {
        this.facultyCode = facultyCode;
    }

    
    @Column(name="faculty_name", nullable=false, length=30)
    public String getFacultyName() {
        return this.facultyName;
    }
    
    public void setFacultyName(String facultyName) {
        this.facultyName = facultyName;
    }

    
    @Column(name="faculty_email", nullable=false, length=30)
    public String getFacultyEmail() {
        return this.facultyEmail;
    }
    
    public void setFacultyEmail(String facultyEmail) {
        this.facultyEmail = facultyEmail;
    }

    
    @Column(name="faculty_phone", nullable=false, length=11)
    public String getFacultyPhone() {
        return this.facultyPhone;
    }
    
    public void setFacultyPhone(String facultyPhone) {
        this.facultyPhone = facultyPhone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tspFaculty")
    public Set<ExamSchedule> getExamSchedules() {
        return this.examSchedules;
    }
    
    public void setExamSchedules(Set<ExamSchedule> examSchedules) {
        this.examSchedules = examSchedules;
    }




}


