package info.javaknowledge.projectstarter.domain;
// Generated Jan 25, 2018 6:45:30 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TspInfo generated by hbm2java
 */
@Entity
@Table(name="tsp_info"
    ,catalog="tsp"
)
public class TspInfo  implements java.io.Serializable {


     private Integer tspId;
     private String tspName;
     private String tspAddress;
     private String tspPhone;
     private String tspEmail;
     private String tspLocation;
     private Set<BatchInfo> batchInfos = new HashSet<BatchInfo>(0);
     private Set<LoginInfo> loginInfos = new HashSet<LoginInfo>(0);
     private Set<ExamSchedule> examSchedules = new HashSet<ExamSchedule>(0);
     private Set<TspFaculty> tspFaculties = new HashSet<TspFaculty>(0);
     private Set<StudentInfo> studentInfos = new HashSet<StudentInfo>(0);
     private Set<TspTc> tspTcs = new HashSet<TspTc>(0);

    public TspInfo() {
    }

	
    public TspInfo(String tspName, String tspAddress, String tspPhone, String tspEmail, String tspLocation) {
        this.tspName = tspName;
        this.tspAddress = tspAddress;
        this.tspPhone = tspPhone;
        this.tspEmail = tspEmail;
        this.tspLocation = tspLocation;
    }
    public TspInfo(String tspName, String tspAddress, String tspPhone, String tspEmail, String tspLocation, Set<BatchInfo> batchInfos, Set<LoginInfo> loginInfos, Set<ExamSchedule> examSchedules, Set<TspFaculty> tspFaculties, Set<StudentInfo> studentInfos, Set<TspTc> tspTcs) {
       this.tspName = tspName;
       this.tspAddress = tspAddress;
       this.tspPhone = tspPhone;
       this.tspEmail = tspEmail;
       this.tspLocation = tspLocation;
       this.batchInfos = batchInfos;
       this.loginInfos = loginInfos;
       this.examSchedules = examSchedules;
       this.tspFaculties = tspFaculties;
       this.studentInfos = studentInfos;
       this.tspTcs = tspTcs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tsp_id", unique=true, nullable=false)
    public Integer getTspId() {
        return this.tspId;
    }
    
    public void setTspId(Integer tspId) {
        this.tspId = tspId;
    }

    
    @Column(name="tsp_name", nullable=false, length=30)
    public String getTspName() {
        return this.tspName;
    }
    
    public void setTspName(String tspName) {
        this.tspName = tspName;
    }

    
    @Column(name="tsp_address", nullable=false, length=30)
    public String getTspAddress() {
        return this.tspAddress;
    }
    
    public void setTspAddress(String tspAddress) {
        this.tspAddress = tspAddress;
    }

    
    @Column(name="tsp_phone", nullable=false, length=11)
    public String getTspPhone() {
        return this.tspPhone;
    }
    
    public void setTspPhone(String tspPhone) {
        this.tspPhone = tspPhone;
    }

    
    @Column(name="tsp_email", nullable=false, length=30)
    public String getTspEmail() {
        return this.tspEmail;
    }
    
    public void setTspEmail(String tspEmail) {
        this.tspEmail = tspEmail;
    }

    
    @Column(name="tsp_location", nullable=false, length=50)
    public String getTspLocation() {
        return this.tspLocation;
    }
    
    public void setTspLocation(String tspLocation) {
        this.tspLocation = tspLocation;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tspInfo")
//    @JsonIgnore
    public Set<BatchInfo> getBatchInfos() {
        return this.batchInfos;
    }
    
    public void setBatchInfos(Set<BatchInfo> batchInfos) {
        this.batchInfos = batchInfos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tspInfo")
    
//    @JsonIgnore
    public Set<LoginInfo> getLoginInfos() {
        return this.loginInfos;
    }
    
    public void setLoginInfos(Set<LoginInfo> loginInfos) {
        this.loginInfos = loginInfos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tspInfo")
//    @JsonIgnore
    public Set<ExamSchedule> getExamSchedules() {
        return this.examSchedules;
    }
    
    public void setExamSchedules(Set<ExamSchedule> examSchedules) {
        this.examSchedules = examSchedules;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tspInfo")
//    @JsonIgnore
    public Set<TspFaculty> getTspFaculties() {
        return this.tspFaculties;
    }
    
    public void setTspFaculties(Set<TspFaculty> tspFaculties) {
        this.tspFaculties = tspFaculties;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tspInfo")
    //@JsonIgnore
    public Set<StudentInfo> getStudentInfos() {
        return this.studentInfos;
    }
    
    public void setStudentInfos(Set<StudentInfo> studentInfos) {
        this.studentInfos = studentInfos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tspInfo")
        
    public Set<TspTc> getTspTcs() {
        return this.tspTcs;
    }
    
    public void setTspTcs(Set<TspTc> tspTcs) {
        this.tspTcs = tspTcs;
    }




}


