package info.javaknowledge.projectstarter.domain;
// Generated Jan 25, 2018 6:45:30 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TspTc generated by hbm2java
 */
@Entity
@Table(name="tsp_tc"
    ,catalog="tsp"
)
public class TspTc  implements java.io.Serializable {


     private Integer tcId;
     private TspInfo tspInfo;
     private String tcName;
     private String tcEmail;
     private String tcPhone;

    public TspTc() {
    }

    public TspTc(TspInfo tspInfo, String tcName, String tcEmail, String tcPhone) {
       this.tspInfo = tspInfo;
       this.tcName = tcName;
       this.tcEmail = tcEmail;
       this.tcPhone = tcPhone;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tc_id", unique=true, nullable=false)
    public Integer getTcId() {
        return this.tcId;
    }
    
    public void setTcId(Integer tcId) {
        this.tcId = tcId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tsp_id", nullable=false)
    public TspInfo getTspInfo() {
        return this.tspInfo;
    }
    
    public void setTspInfo(TspInfo tspInfo) {
        this.tspInfo = tspInfo;
    }

    
    @Column(name="tc_name", nullable=false, length=30)
    public String getTcName() {
        return this.tcName;
    }
    
    public void setTcName(String tcName) {
        this.tcName = tcName;
    }

    
    @Column(name="tc_email", nullable=false, length=30)
    public String getTcEmail() {
        return this.tcEmail;
    }
    
    public void setTcEmail(String tcEmail) {
        this.tcEmail = tcEmail;
    }

    
    @Column(name="tc_phone", nullable=false, length=11)
    public String getTcPhone() {
        return this.tcPhone;
    }
    
    public void setTcPhone(String tcPhone) {
        this.tcPhone = tcPhone;
    }




}


